# 本地开发配置（不要提交到 Git！）
# 仅用于本地开发，生产环境使用环境变量

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tFpjgBCdymQfjVb4TZT
    accessKeySecret: 7O7nq7rJMf5nOFWQ15h5MXbCrgezQr
    bucketName: sheepmusic
    urlPrefix: https://sheepmusic.oss-cn-hangzhou.aliyuncs.com/


